language: perl
arch:
  - arm64
matrix:
  include:
    - dist: xenial
      perl: 5.24
      env:
        - EXTRA_TRAVIS_HELPER_CPAN_PM_OPTS="-mirrorurl https://cpan.metacpan.org/ -mirrorurl http://cpan.cpantesters.org/"
    - dist: bionic
      perl: 5.26
    - dist: focal
      perl: 5.32

#    - perl: "5.30"
#      dist: bionic
#    - perl: "5.26"
#      dist: xenial
#    - perl: "5.8"
#      dist: trusty
#    - perl: "5.24"
#      dist: xenial
#    - perl: "5.14"
#      dist: trusty
### XXX does not work yet; probably need to configure local::lib
### XXX currently fails on CPAN.pm upgrade --- writes to /usr/bin are not permitted
### XXX so an old non-plugin capable CPAN.pm is used (version 2.00 or so)
##    - perl: "5.18"
##      os: osx
#    - perl: "5.18"
#      env:
#        - EXTRA_TRAVIS_HELPER_CPAN_PM_OPTS="-mirrorurl https://cpan.metacpan.org/ -mirrorurl http://cpan.cpantesters.org/"
#      dist: trusty
#    - perl: "5.14"
#      dist: trusty
#    - perl: "5.10"
#      dist: trusty
#    - perl: "5.20-shrplib"
#      dist: xenial
##  allow_failures:
#### XXX Prima 1.59 does not compile: https://rt.cpan.org/Ticket/Display.html?id=132752
##    - dist: trusty

before_install:
  - ./travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps --sysdeps-branch=master $EXTRA_TRAVIS_HELPER_CPAN_PM_OPTS
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then (cd /etc/apt/sources.list.d && sudo rm -f mongodb.list google-chrome.list cassandra.list github_git-lfs.list couchdb.list pgdg.list); fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update -qq; fi

install:
  - cpan File::LibMagic Curses DB_File GD Imager Linux::Inotify2 Pango Tk WWW::Curl
  # XML::LibXML tries to /System/Library/Perl/Extras/5.18/XML/SAX/ParserDetails.ini which is not allowed
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cpan XML::LibXML; fi
  # minimum perl version is 5.12; fails on arm64, see also http://www.cpantesters.org/cpan/report/6f5410aa-cf6f-11eb-976e-955d73356c18
  - if [[ "$TRAVIS_PERL_VERSION" != "5.8" && "$TRAVIS_PERL_VERSION" != "5.10" && "$TRAVIS_CPU_ARCH" != "arm64" ]] ; then cpan Prima; fi

script:
  - perl -c travis-helper-cpan-pm
  - perl -MCurses -e1
  - perl -MDB_File -e1
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then perl -MFile::LibMagic -e1; fi
  - perl -MGD -e1
  - perl -MImager -e1
  - perl -MLinux::Inotify2 -e1
  - perl -MPango -e1
## XXX fails without DISPLAY
#  - perl -MPrima -e1
  - perl -MTk -e1
  - perl -MWWW::Curl -e1
  - perl -MXML::LibXML -e1

branches:
  except:
    - /appveyor/
    - /github-actions/
