name: Test specific CPAN module
run-name: Test ${{ inputs.module }}

on:
  workflow_dispatch:
    inputs:
      module:
        type: string
        required: true
      include-distroprefs:
        type: boolean
        default: true
      include-sysdeps:
        type: boolean
        default: true
      distroprefs-branch:
        type: string
        default: master
      sysdeps-branch:
        type: string
        default: master

jobs:
  test-module:
    name: on ${{ matrix.container || matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            container: ~
          - os: 'macos-14'
            container: ~
          - os: 'ubuntu-20.04'
            container: ~
          - os: 'ubuntu-22.04'
            container: ~
          - os: 'ubuntu-24.04'
            container: ~
          # another ubuntu as a container, not runner
          - os: 'ubuntu-latest'
            container: ubuntu:24.04
          # fedora: use the minimum and maximum supported versions
          - os: 'ubuntu-latest'
            container: fedora:38
          - os: 'ubuntu-latest'
            container: fedora:40
          - os: 'ubuntu-latest'
            container: centos:7
          ## XXX needs more work
          #- os: 'ubuntu-latest'
          #  container: debian:stretch
          - os: 'ubuntu-latest'
            container: debian:buster
          - os: 'ubuntu-latest'
            container: debian:bookworm
          - os: 'ubuntu-latest'
            container: debian:trixie
          ## XXX would work if CPAN::Plugin::Sysdeps had alpine support
          #- os: 'ubuntu-latest'
          #  container: alpine:latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: eserte/ci-helper-cpan-pm
        path: ci-helper-cpan-pm
      if: matrix.container == 'centos:7'
    - uses: actions/checkout@v4
      with:
        repository: eserte/ci-helper-cpan-pm
        path: ci-helper-cpan-pm
      if: matrix.container != 'centos:7'

    - name: "CentOS: install epel"
      run: |
        yum -y install epel-release
      if: "startsWith(matrix.container, 'centos')"

    - name: "rpm-based systems: install perl, CPAN.pm, git..."
      run: |
        yum -y install "perl(CPAN)" "perl(Test::More)" "perl(Parse::CPAN::Meta)" git make gcc patch
      if: "startsWith(matrix.container, 'fedora') || startsWith(matrix.container, 'centos')"

    - name: "apt-based systems: install perl, CPAN.pm, git, make, cc..."
      run: |
        apt-get update -yq && apt-get install -yqq perl git make gcc g++
      if: "startsWith(matrix.container, 'debian') || startsWith(matrix.container, 'ubuntu')"

    - name: "apk-based systems: install perl, CPAN.pm, git..."
      run: |
        apk update -q && apk add -q perl perl-utils git make gcc
      if: "startsWith(matrix.container, 'alpine')"

    - name: "perlbrew-based systems: add Perl executable path to GITHUB_PATH"
      run: |
        echo "$(perl -MConfig -e 'print $Config{sitebin}')" >> $GITHUB_PATH
      if: "startsWith(matrix.os, 'macos')"

    - name: apt hacks
      # the already installed libgd3 conflicts with libgd-dev to be installed
      # also, /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        if [ -d /etc/apt/sources.list.d ]; then
          echo "Remove additional apt sources..."
          sudocmd=$( [ "$(id -u)" -ne 0 ] && echo "sudo" || echo "" )
          $sudocmd rm -f /etc/apt/sources.list.d/*.list
          $sudocmd apt-get update -qq
          $sudocmd apt-get remove -y libgd3 nginx
        fi

    - name: before_install
      run: |
        distroprefs_opts=
        if [ ${{ inputs.include-distroprefs }} = 'true' ]
        then
            distroprefs_opts='--distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --distroprefs-branch=${{ inputs.distroprefs-branch }}'
        fi
        sysdeps_opts=
        if [ ${{ inputs.include-sysdeps }} = 'true' ]
        then
            sysdeps_opts='--enable-sysdeps --sysdeps-branch=${{ inputs.sysdeps-branch }}'
        fi
        set -ex
        $GITHUB_WORKSPACE/ci-helper-cpan-pm/ci-helper-cpan-pm --no-test $distroprefs_opts $sysdeps_opts
    - name: cpan-sysdeps check
      continue-on-error: true
      run: |
        cpan-sysdeps --cpanmod ${{ inputs.module }}
    - name: cpan-sysdeps dry-run commands
      continue-on-error: true
      run: |
        cpan-sysdeps --cpanmod ${{ inputs.module }} --dry-run
    - name: install ${{ inputs.module }}
      run: |
        cpan ${{ inputs.module }}
    - name: check ${{ inputs.module }}
      run: |
        $GITHUB_WORKSPACE/ci-helper-cpan-pm/gh-mod-check ${{ inputs.module }}

  test-module-freebsd:
    name: on freebsd ${{ matrix.osvers }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - osvers: '13.2'
          - osvers: '14.0'
    steps:
    - uses: actions/checkout@v4
      with:
        repository: eserte/ci-helper-cpan-pm
        path: ci-helper-cpan-pm

    - uses: cross-platform-actions/action@v0.24.0
      with:
        operating_system: freebsd
        version: '${{ matrix.osvers }}'
        shell: bash
        sync_files: runner-to-vm
        run: |
          sudo pkg update
          sudo pkg install -y perl5 git

          distroprefs_opts=
          if [ ${{ inputs.include-distroprefs }} = 'true' ]
          then
              distroprefs_opts='--distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --distroprefs-branch=${{ inputs.distroprefs-branch }}'
          fi
          sysdeps_opts=
          if [ ${{ inputs.include-sysdeps }} = 'true' ]
          then
              sysdeps_opts='--enable-sysdeps --sysdeps-branch=${{ inputs.sysdeps-branch }}'
          fi
          set -ex
          $GITHUB_WORKSPACE/ci-helper-cpan-pm/ci-helper-cpan-pm --no-test $distroprefs_opts $sysdeps_opts

          cpan ${{ inputs.module }}

          $GITHUB_WORKSPACE/ci-helper-cpan-pm/gh-mod-check ${{ inputs.module }}
