name: Test specific CPAN module
run-name: Test ${{ inputs.module }}

on:
  workflow_dispatch:
    inputs:
      module:
        type: string
        required: true
      include-distroprefs:
        type: boolean
        default: true
      include-sysdeps:
        type: boolean
        default: true
      sysdeps-branch:
        type: string
        default: master

jobs:
  test-module:
    name: on ${{ matrix.container || matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: 'ubuntu-20.04'
            container: ~
          - os: 'ubuntu-22.04'
            container: ~
          - os: 'ubuntu-latest'
            container: fedora:39
          - os: 'ubuntu-latest'
            container: centos:7
          ## XXX needs more work
          #- os: 'ubuntu-latest'
          #  container: debian:stretch
          - os: 'ubuntu-latest'
            container: debian:buster
          - os: 'ubuntu-latest'
            container: debian:bookworm

    steps:
    - uses: actions/checkout@v3
      with:
        repository: eserte/ci-helper-cpan-pm
        path: ci-helper-cpan-pm

    - name: "rpm-based systems: install perl, CPAN.pm, git..."
      run: |
        yum -y install "perl(CPAN)" "perl(Test::More)" "perl(Parse::CPAN::Meta)" git make gcc
      if: "startsWith(matrix.container, 'fedora') || startsWith(matrix.container, 'centos')"

    - name: "apt-based systems: install perl, CPAN.pm, git..."
      run: |
        apt-get update -yq && apt-get install -yqq perl git make gcc
      if: "startsWith(matrix.container, 'debian')"

    - name: apt hacks
      # the already installed libgd3 conflicts with libgd-dev to be installed
      # also, /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        if [[ -d /etc/apt/sources.list.d ]]; then
          echo "Remove additional apt sources..."
          sudo rm -f /etc/apt/sources.list.d/*.list
          sudo apt-get update -qq
          sudo apt-get remove -y libgd3 nginx
        fi

    - name: before_install
      run: |
        distroprefs_opts=
        if [ ${{ inputs.include-distroprefs == 'true' }} ]
        then
            distroprefs_opts='--distroprefs=https://github.com/eserte/srezic-cpan-distroprefs'
        fi
        sysdeps_opts=
        if [ ${{ inputs.include-sysdeps == 'true' }} ]
        then
            sysdeps_opts='--enable-sysdeps --sysdeps-branch=${{ inputs.sysdeps-branch }}'
        fi
        set -ex
        $GITHUB_WORKSPACE/ci-helper-cpan-pm/ci-helper-cpan-pm $distroprefs_opts $sysdeps_opts
    - name: install ${{ inputs.module }}
      run: cpan ${{ inputs.module }}
    - name: check ${{ inputs.module }}
      run: perl -M${{ inputs.module }} -e1
